# This file is autogenerated by `make makefile`
.PHONY: default
default: build

Makefile: util/maker.sh
	@util/maker.sh makemakefile

.PHONY: push
push: build dist
	@./util/maker.sh makepush

.PHONY: clean
clean: 
	@./util/maker.sh makeclean

.PHONY: gamelogs
gamelogs: 
	@./util/maker.sh makegamelogs

.PHONY: install-full
install-full: build dist
	@./util/maker.sh makeinstall-full

.PHONY: run
run: dist
	@./util/maker.sh makerun

.PHONY: logs
logs: 
	@./util/maker.sh makelogs

.PHONY: install
install: build dist
	@./util/maker.sh makeinstall

.PHONY: build
build: refasm
	@./util/maker.sh makebuild

.PHONY: preclean
preclean: 
	@./util/maker.sh makepreclean

.PHONY: makefile
makefile: 
	@./util/maker.sh makemakefile

.PHONY: refasm
refasm: 
	@./util/maker.sh makerefasm

.PHONY: dist
dist: build
	@./util/maker.sh makedist

.PHONY: paths
paths: 
	@./util/maker.sh makepaths

